db.url=jdbc:mysql://localhost:3306/tennis_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
db.username=tennis_user
db.password=tennis_pass
db.pool.size=10

server.port=9000
# Turns off useless logs
logging.level.org.springframework=WARN
# Turns off generating graphics on start
spring.main.banner-mode=off
# Initializes components when needed
spring.main.lazy-initialization=true
# Logs for Spring and Jackson
logging.level.org.springframework.web=WARN
logging.level.com.fasterxml.jackson=WARN